### ISSUE TITLE
TIMEZONE( marked as syntax error for DCLGEN COPY

### ISSUE THREAD

**Issue by COBOL-Erik** [BroadcomMFD/code4z#61]
With something like this
EXEC SQL DECLARE MYTAB TABLE                                       
            (CREATION_TIMESTAMP                                                 
                       TIMESTAMP(6) WITHOUT TIME ZONE                           
                                            NOT NULL                            
           ) END-EXEC.
(typically generated by the DCLGEN utility), the first parenthesis after "TIMESTAMP" is marked as a syntax error:
Extraneous input '(' expected {',', ')'} COBOL Language Support - E

This syntax should be supported.

**Comment by zimlu02** [comment]
Hi @COBOL-Erik ,
sorry for this unnoticed ticket.
I have moved this issue to the [COBOL LS GitHub](https://github.com/eclipse/che-che4z-lsp-for-cobol/issues) where we store requests for COBOL LS extension. Please follow this link in order to track the status:
https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/1767
